---
- name: "Download version chosen"
  hosts: localhost
  tasks:
    - name: "Download the tarball"
      get_url:
        url: "https://github.com/derailed/k9s/releases/download/{{version}}/k9s_Linux_amd64.tar.gz"
        dest: /home/rocky